version: 0.2

phases:
  pre_build:
    # Log in to ECR, and get an ECR Loging Token.  Since we have a connection after this point, we will be able to Push the Docker image
    # to ECR at a Later Point. 
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI = ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${IMAGE_REPO_NAME}
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com
  build:
    # Build the Docker Image from Dockerfile.
    # Once the Image has been built, the image tag needs to be updated to specify the Remote ECR Repository Name.
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd userauth            
      - docker build -t ${IMAGE_REPO_NAME} .
      - cd ..
      - docker tag ${IMAGE_REPO_NAME} ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${IMAGE_REPO_NAME}
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${IMAGE_REPO_NAME}
      - printf '[{"name":"auth-micro-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

